#include "VulkanShader.h"
#include "VulkanDevice.h"
#include "shaders_embedded.h" // Generated by CMake

#include <vector>
#include <stdexcept>

VulkanShader::VulkanShader(const VulkanDevice &device,
                           const std::string &vertPath,
                           const std::string &fragPath)
    : deviceRef(device)
{
    // Paths are ignored now that we use embedded data,
    // but we keep the signature for compatibility.
    vertexModule = createShaderModule(CUBE_VERT_SPV);
    fragmentModule = createShaderModule(CUBE_FRAG_SPV);
}

VulkanShader::VulkanShader(const VulkanDevice &device)
    : deviceRef(device)
{
    vertexModule = createShaderModule(CUBE_VERT_SPV);
    fragmentModule = createShaderModule(CUBE_FRAG_SPV);
}

VulkanShader::~VulkanShader()
{
    if (vertexModule)
    {
        deviceRef.getLogicalDevice().destroyShaderModule(vertexModule);
    }
    if (fragmentModule)
    {
        deviceRef.getLogicalDevice().destroyShaderModule(fragmentModule);
    }
}

// Replaced loadModule(string) with a version that takes the embedded vector
vk::ShaderModule VulkanShader::createShaderModule(const std::vector<uint32_t> &code)
{
    if (code.empty())
    {
        throw std::runtime_error("Embedded shader code is empty!");
    }

    vk::ShaderModuleCreateInfo createInfo;
    createInfo.codeSize = code.size() * sizeof(uint32_t); // Total bytes
    createInfo.pCode = code.data();                       // Pointer to uint32_t array

    return deviceRef.getLogicalDevice().createShaderModule(createInfo);
}

// If your VulkanShader.h still defines loadModule(string),
// you can implement it as a dummy or have it call the embedded version.
vk::ShaderModule VulkanShader::loadModule(const std::string &path)
{
    // For a single-file EXE, we ignore the path and return the default embedded modules
    if (path.find(".vert") != std::string::npos)
        return createShaderModule(CUBE_VERT_SPV);
    return createShaderModule(CUBE_FRAG_SPV);
}