#include "Texture.h"
#include "../vulkan/VulkanDevice.h"
#include "embedded_texture.h" // Generated by CMake
#include <stb_image.h>
#include <stdexcept>

Texture::Texture(const VulkanDevice &device, const std::string &filename)
    : deviceRef(device)
{
    // Note: filename is now ignored because we are loading from memory,
    // but we keep the signature for compatibility with your existing SceneBuilder.
    createImage(filename);
    createImageView();
    createSampler();
}

Texture::~Texture()
{
    deviceRef.getLogicalDevice().destroySampler(sampler);
    deviceRef.getLogicalDevice().destroyImageView(imageView);
    deviceRef.getLogicalDevice().destroyImage(image);
    deviceRef.getLogicalDevice().freeMemory(imageMemory);
}

void Texture::createImage(const std::string &filename)
{
    int texWidth, texHeight, texChannels;

    // Flip the image vertically on load to match Vulkan's UV coordinate system
    stbi_set_flip_vertically_on_load(true);

    // === Load from embedded memory instead of disk ===
    stbi_uc *pixels = stbi_load_from_memory(
        CONTAINER_JPG_DATA.data(),
        static_cast<int>(CONTAINER_JPG_DATA.size()),
        &texWidth, &texHeight, &texChannels, STBI_rgb_alpha);

    if (!pixels)
    {
        throw std::runtime_error("failed to load embedded texture image!");
    }

    vk::DeviceSize imageSize = texWidth * texHeight * 4;
    auto device = deviceRef.getLogicalDevice();

    // === Create staging buffer ===
    vk::BufferCreateInfo stagingBufferInfo;
    stagingBufferInfo.size = imageSize;
    stagingBufferInfo.usage = vk::BufferUsageFlagBits::eTransferSrc;
    stagingBufferInfo.sharingMode = vk::SharingMode::eExclusive;

    vk::Buffer stagingBuffer = device.createBuffer(stagingBufferInfo);

    vk::MemoryRequirements memRequirements = device.getBufferMemoryRequirements(stagingBuffer);
    vk::MemoryAllocateInfo allocInfo(memRequirements.size,
                                     deviceRef.findMemoryType(memRequirements.memoryTypeBits,
                                                              vk::MemoryPropertyFlagBits::eHostVisible | vk::MemoryPropertyFlagBits::eHostCoherent));
    vk::DeviceMemory stagingMemory = device.allocateMemory(allocInfo);
    device.bindBufferMemory(stagingBuffer, stagingMemory, 0);

    void *data = device.mapMemory(stagingMemory, 0, imageSize);
    memcpy(data, pixels, static_cast<size_t>(imageSize));
    device.unmapMemory(stagingMemory);

    stbi_image_free(pixels);

    // === Create tiled image ===
    vk::ImageCreateInfo imageInfo;
    imageInfo.imageType = vk::ImageType::e2D;
    imageInfo.format = vk::Format::eR8G8B8A8Srgb;
    imageInfo.extent = vk::Extent3D(static_cast<uint32_t>(texWidth), static_cast<uint32_t>(texHeight), 1);
    imageInfo.mipLevels = 1;
    imageInfo.arrayLayers = 1;
    imageInfo.samples = vk::SampleCountFlagBits::e1;
    imageInfo.tiling = vk::ImageTiling::eOptimal;
    imageInfo.usage = vk::ImageUsageFlagBits::eTransferDst | vk::ImageUsageFlagBits::eSampled;
    imageInfo.sharingMode = vk::SharingMode::eExclusive;
    imageInfo.initialLayout = vk::ImageLayout::eUndefined;

    image = device.createImage(imageInfo);

    memRequirements = device.getImageMemoryRequirements(image);
    allocInfo = vk::MemoryAllocateInfo(memRequirements.size,
                                       deviceRef.findMemoryType(memRequirements.memoryTypeBits, vk::MemoryPropertyFlagBits::eDeviceLocal));
    imageMemory = device.allocateMemory(allocInfo);
    device.bindImageMemory(image, imageMemory, 0);

    // === One-time command buffer for layout transition and copy ===
    vk::CommandPoolCreateInfo poolInfo;
    poolInfo.queueFamilyIndex = deviceRef.getGraphicsQueueFamily();
    vk::CommandPool commandPool = device.createCommandPool(poolInfo);

    vk::CommandBufferAllocateInfo cmdAllocInfo(commandPool, vk::CommandBufferLevel::ePrimary, 1);
    vk::CommandBuffer commandBuffer = device.allocateCommandBuffers(cmdAllocInfo)[0];

    vk::CommandBufferBeginInfo beginInfo(vk::CommandBufferUsageFlagBits::eOneTimeSubmit);
    commandBuffer.begin(beginInfo);

    // Transition to TRANSFER_DST
    vk::ImageMemoryBarrier barrier;
    barrier.oldLayout = vk::ImageLayout::eUndefined;
    barrier.newLayout = vk::ImageLayout::eTransferDstOptimal;
    barrier.srcAccessMask = vk::AccessFlags();
    barrier.dstAccessMask = vk::AccessFlagBits::eTransferWrite;
    barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.image = image;
    barrier.subresourceRange = vk::ImageSubresourceRange(vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1);

    commandBuffer.pipelineBarrier(vk::PipelineStageFlagBits::eTopOfPipe, vk::PipelineStageFlagBits::eTransfer, vk::DependencyFlags(), {}, {}, barrier);

    // Copy staging buffer to image
    vk::BufferImageCopy copyRegion;
    copyRegion.bufferOffset = 0;
    copyRegion.imageSubresource = vk::ImageSubresourceLayers(vk::ImageAspectFlagBits::eColor, 0, 0, 1);
    copyRegion.imageExtent = vk::Extent3D(static_cast<uint32_t>(texWidth), static_cast<uint32_t>(texHeight), 1);

    commandBuffer.copyBufferToImage(stagingBuffer, image, vk::ImageLayout::eTransferDstOptimal, copyRegion);

    // Transition to SHADER_READ_ONLY
    barrier.srcAccessMask = vk::AccessFlagBits::eTransferWrite;
    barrier.dstAccessMask = vk::AccessFlagBits::eShaderRead;
    barrier.oldLayout = vk::ImageLayout::eTransferDstOptimal;
    barrier.newLayout = vk::ImageLayout::eShaderReadOnlyOptimal;

    commandBuffer.pipelineBarrier(vk::PipelineStageFlagBits::eTransfer, vk::PipelineStageFlagBits::eFragmentShader, vk::DependencyFlags(), {}, {}, barrier);

    commandBuffer.end();

    vk::SubmitInfo submitInfo(0, nullptr, nullptr, 1, &commandBuffer);
    deviceRef.getGraphicsQueue().submit(submitInfo);
    deviceRef.getGraphicsQueue().waitIdle();

    device.freeCommandBuffers(commandPool, commandBuffer);
    device.destroyCommandPool(commandPool);
    device.destroyBuffer(stagingBuffer);
    device.freeMemory(stagingMemory);
}

void Texture::createImageView()
{
    vk::ImageViewCreateInfo viewInfo;
    viewInfo.image = image;
    viewInfo.viewType = vk::ImageViewType::e2D;
    viewInfo.format = vk::Format::eR8G8B8A8Srgb;
    viewInfo.subresourceRange = vk::ImageSubresourceRange(vk::ImageAspectFlagBits::eColor, 0, 1, 0, 1);

    imageView = deviceRef.getLogicalDevice().createImageView(viewInfo);
}

void Texture::createSampler()
{
    vk::SamplerCreateInfo samplerInfo;
    samplerInfo.magFilter = vk::Filter::eLinear;
    samplerInfo.minFilter = vk::Filter::eLinear;
    samplerInfo.mipmapMode = vk::SamplerMipmapMode::eLinear;
    samplerInfo.addressModeU = vk::SamplerAddressMode::eRepeat;
    samplerInfo.addressModeV = vk::SamplerAddressMode::eRepeat;
    samplerInfo.addressModeW = vk::SamplerAddressMode::eRepeat;
    samplerInfo.minLod = 0.0f;
    samplerInfo.maxLod = 0.0f;
    samplerInfo.borderColor = vk::BorderColor::eIntOpaqueBlack;

    sampler = deviceRef.getLogicalDevice().createSampler(samplerInfo);
}